waves: waves.h waves.c main_waves.c
	clang -Wall -lm -o waves waves.c main_waves.c
evidence_waves: waves.h waves.c evidence_waves.c
	clang -Wall -lm -o evidence_waves waves.c evidence_waves.c
clean:
	rm -f evidence_waves waves *.o *~